fixed prompt and completion

diff --git a/_bashrc b/_bashrc
--- a/_bashrc
+++ b/_bashrc
@@ -23,7 +23,8 @@ export TIMEFORMAT=$'\nreal %3R	user %3U	sys %3S	pcpu %P\n'
 set -o ignoreeof                 # don't use ^D to exit
 set -o noclobber
 set -o notify                    # don't wait for job termination notification
-#set -o vi                        # use VI for editing
+#set -o vi                        # this breaks bash completion
+set editing-mode vi
 set nocompatible
 set nodosfilewarnings            # turn off dos file warnings
 shopt -s cdable_vars
@@ -547,24 +548,42 @@ fi
 #------------------------------------------------------------------------------
 # setup colors and prompt
 #------------------------------------------------------------------------------
-BLACK='\e[0;30m'        # black
-RED='\e[0;31m'          # Red
-GREEN='\e[0;32m'        # Green
-YELLOW='\e[0;33m'       # Yellow
-BLUE='\e[0;34m'         # Blue
-PURPLE='\e[0;35m'       # Purple
-CYAN='\e[0;36m'         # Cyan
-WHITE='\e[0;37m'        # White
-NC='\e[0m'       # Text Reset
-
-echo -e "${CYAN}This is BASH ${RED}${BASH_VERSION%.*}${CYAN}${NC}"
-date
-
 # Set up syntax highlighting for 'less' (requires source-highlight package)
 # See http://www.gnu.org/software/src-highlite/source-highlight.html
 export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
 export LESS=' -R '
 
-#PS1="${CYAN}[\d \A][\w]${NC}\n\$ "
-export PROMPT_COMMAND='export H1="`history 1|sed -e "s/^[\ 0-9]*//; s/[\d0\d31\d34\d39\d96\d127]*//g; s/\(.\{1,50\}\).*$/\1/g"`";history -a;echo -e "sgr0\ncnorm\nrmso"|tput -S'
-export PS1='\n\e[1;30m[\j:\!\e[1;30m]\e[0;36m \@ \d \e[1;30m[\e[1;34m\u@\H\e[1;30m:\e[0;37m`tty 2>/dev/null` \e[0;32m+${SHLVL}\e[1;30m] \e[1;37m\w\e[0;37m\[\033]0;[ ${H1}... ] \w - \u@\H +$SHLVL @`tty 2>/dev/null`\007\]\n\[\]\$ '
+set_prompt () {
+    Last_Command=$? # Must come first!
+    local Blue='\[\e[01;34m\]'
+    local White='\[\e[01;37m\]'
+    local Red='\[\e[01;31m\]'
+    local Green='\[\e[01;32m\]'
+    local Reset='\[\e[00m\]'
+    local FancyX='\342\234\227'
+    local Checkmark='\342\234\223'
+
+    # Add a bright white exit status for the last command
+    PS1="$White\$? "
+    # If it was successful, print a green check mark. Otherwise, print
+    # a red X.
+    if [[ $Last_Command == 0 ]]; then
+        PS1+="$Green$Checkmark "
+    else
+        PS1+="$Red$FancyX "
+    fi
+
+	# show the command number for reference
+	PS1+="[\#]" # should I use \!
+    # If root, just print the host in red. Otherwise, print the current user
+    # and host in green.
+    if [[ $EUID == 0 ]]; then
+        PS1+="[$Red\\h]"
+    else
+        PS1+="[$Green\\u@\\h]"
+    fi
+    # Print the working directory and prompt marker in blue, and reset
+    # the text color to the default.
+	PS1+="$Blue[\d \A][\w]$Reset\n\$ "
+}
+PROMPT_COMMAND='set_prompt'
